training_percent = 0.8
testing_percent = 0.2
dataset_path = "Phishing_Email.csv"
intended_device = "gpu" #cpu or gpu
learning_rate = 4e-5
rand_seed = 2025
max_len = 80
batch_size = 16
epochs = 1